### ISSUE TITLE
벽람 챈에서 글 보고 만듬

### ISSUE THREAD

**Issue by aga97** [AzurLaneKorWiki/AzurLaneKorWiki.github.io#1]
하는데 재밌을 것 같아서 참여해봄.

일단 기획이나 계획 부분을 물어보고 싶은데 요게 이렇게 글 쓰고 답변 달고 하는 식으로는 좀 한계가 있을 것 같아서

카톡 익명 채팅? 디코? 이런걸로 시간 맞을 때 질문 좀 해도 괜찮을까? 물어볼것만 물어보고 폭파 시키면 될 것 같은데

**Comment by AzurLaneKorWiki** [comment]
걘적으로 소전 가이드북쪽에서 문제 생긴걸 봐서 디코랑 카톡은 좀 피했으면 함

한다 해도 갤럼들하고 완장들한테 허락을 받아야될 것 같은데

**Comment by aga97** [comment]
@AzurLaneKorWiki 

그러면 걍 이슈에서 씀

일단 먼저 물어보고 싶은게

1. 기술 스택
 => html css js는 어느정도 쓸수 있는 것 같고 이 외에 웹 관련 기술 스택 있음?
2. node로 이전할 의향
 => 어제 글 보고서 리액트로 프로젝트 세팅 대충 해놓은게 있어서 물어봄
3. DB 사용 여부
 => 데이터가 많은 편은 아니라 굳이 사용안해도 될것 같긴한데 혹시 모르니 물어봄

그리고 기획? 계획? 에 대해서 간단히 설명해 주면 좋겠음

**Comment by AzurLaneKorWiki** [comment]
이게... 내가 그쪽보다 훨씬 개발 능력 자체가 떨어질 것 같음
HTML도 흥미가 생겨서 최근에 독학한거지 본래 내가 웹쪽은 아녔으니까

자바스크립트도 겉핥기라 JS쪽에는 내가 도움이 안될거임
node.js도 당연히 제대로 못써먹고

DB는 고화질 일러 쟁겨둘거 아니라면 굳이 필요는 없을 것 같음

우선 기획은 생각해보고는 있는데
일단 건조시트랑 뉴비 가이드 작성하면서 기반 좀 채워두면서 좀 구체적으로 생각좀 해보려고 함

https://slaimuda.github.io/ectl/#/home
글섭 티어사이트랑 UI는 비슷하게 하면서 추가적으로 정보 채워넣는 방향으로 갈 것 같음

일이 커질지는 몰랏내;

**Comment by AzurLaneKorWiki** [comment]
FrontPage랑 뉴비 가이드에 링크걸려있는건 전부 임시로 해둔 것
전부 뜯어고쳐도 됨

**Comment by aga97** [comment]
@AzurLaneKorWiki 
그럼 일단 리포지토리 초대좀 해주고

이거 푸시하면 wiki.io에 바로 적용되는건 아니지?

**Comment by AzurLaneKorWiki** [comment]
초대했음
아마 바로 적용될거임
